import type { Config } from 'tailwindcss';

export default {
  content: ['./app/**/*.{js,ts,jsx,tsx,mdx}', './pages/**/*.{js,ts,jsx,tsx,mdx}', './components/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        'secondary-container': '#fed488',
        'on-primary-fixed': '#1c1b1b',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#c8c6c2',
        'inverse-on-surface': '#f2f0f0',
        'surface-container-lowest': '#ffffff',
        'tertiary': '#000000',
        'on-primary-container': '#858383',
        'surface-variant': '#e4e2e2',
        'background': '#fbf9f8',
        'on-surface': '#1b1c1c',
        'surface-dim': '#dbd9d9',
        'on-primary': '#ffffff',
        'secondary-fixed-dim': '#e9c176',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#1b1c19',
        'surface-container-high': '#eae8e7',
        'tertiary-container': '#1b1c19',
        'surface-container': '#efeded',
        'secondary': '#775a19',
        'surface-tint': '#5f5e5e',
        'on-primary-fixed-variant': '#474646',
        'outline-variant': '#c4c7c7',
        'primary-fixed-dim': '#c8c6c5',
        'primary': '#000000',
        'surface': '#fbf9f8',
        'on-secondary-fixed': '#261900',
        'primary-fixed': '#e5e2e1',
        'error-container': '#ffdad6',
        'surface-container-highest': '#e4e2e2',
        'on-secondary-container': '#785a1a',
        'on-tertiary-fixed-variant': '#474744',
        'surface-bright': '#fbf9f8',
        'outline': '#747878',
        'primary-container': '#1c1b1b',
        'secondary-fixed': '#ffdea5',
        'on-secondary-fixed-variant': '#5d4201',
        'inverse-surface': '#303030',
        'on-surface-variant': '#444748',
        'error': '#ba1a1a',
        'tertiary-fixed': '#e4e2dd',
        'inverse-primary': '#c8c6c5',
        'on-background': '#1b1c1c',
        'on-error': '#ffffff',
        'on-tertiary-container': '#848480',
        'surface-container-low': '#f5f3f3',
        'on-secondary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '80px',
        'margin-mobile': '20px',
        'stack-md': '32px',
        'gutter': '32px',
        'stack-xl': '120px',
        'stack-lg': '64px',
      },
      fontFamily: {
        'display-lg': ['Georgia', 'serif'],
        'label-caps': ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['Georgia', 'serif'],
        'headline-lg-mobile': ['Georgia', 'serif'],
        'body-md': ['Literata', 'serif'],
        'meta': ['Literata', 'serif'],
        'body-lg': ['Literata', 'serif'],
        'headline-lg': ['Georgia', 'serif'],
        serif: ['Georgia', 'serif'],
        sans: ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
        'headline-md': ['28px', { lineHeight: '1.3', fontWeight: '400' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'meta': ['14px', { lineHeight: '1.4', fontWeight: '400' }],
        'body-lg': ['20px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '1.2', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
} satisfies Config;
